### ISSUE TITLE
Hot Swap Connection not working

### ISSUE THREAD

**Issue by sscott0203** [MikeCarlo/BusinessOps#10]
This was all working fine until the latest version of business ops.  PowerShell window opens briefly, but I never get the hot swap connection menu to pop-up.  I have elevated PowerShell permissions for my user name.  I have tried, uninstalling and re-installing without success.

**Comment by sscott0203** [comment]
I may not have uninstalled Business Ops V1 before installing V2 and its been broke ever since V2

**Comment by floari** [comment]
Same problem here. Fresh installation of Business Ops V2 but Hot Swap Connections not working. Elevated Permissions already set.

**Comment by MikeCarlo** [comment]
I have been able to replicate the issue. Tagging Steve as the creator of this tool to see if we can sort out the issue.

**Comment by sscott0203** [comment]
Thanks Mike, appreciate it

**Comment by MikeCarlo** [comment]
Issue has been resolved.  Json files required additional string formatting.
