### ISSUE TITLE
Installing, please wait...

### ISSUE THREAD

**Issue by awg04** [MikeCarlo/BusinessOps#12]
I'm Having issues installing BusinessOps on my machine for the first time. I've tried everything. Deleted all my json files in external tools, uninstalled Dax Studio & tabular editor, tried installing as admin, tried multiple versions, all the same thing.. it gets stuck 3/4 of the way on the install prompt:
![v2 0 2](https://user-images.githubusercontent.com/26827979/151637752-f129ccc0-42a4-42ca-bfc2-c58eef753b84.png)
![v3 0 1](https://user-images.githubusercontent.com/26827979/151637769-c6f17064-0ea1-41b4-8593-8622b09d4cd1.png)

**Comment by JamesDBartlett3** [comment]
@awg04 Several new versions of Business Ops have been released since you opened this issue. Have you downloaded [the latest version](https://powerbi.tips/product/business-ops/) and tried again?

**Comment by awg04** [comment]
Working fine now :) thanks!
