### ISSUE TITLE
Please update Metadata Translator

### ISSUE THREAD

**Issue by mrkorki** [MikeCarlo/BusinessOps#13]
Hi Developers,

Any chance you could update Metadata Translator in this awsome Business Ops tool?
Recently Kay Unkroth added support for hierarchy levels - it would be great to use this capability.
https://github.com/microsoft/Analysis-Services/commit/2bc4805910830391a470954dab1f6f63d2e7997b

All best,
Lukas

**Comment by JamesDBartlett3** [comment]
Hi @mrkorki, 

Thanks for reaching out. We're aware of the update to Metadata Translator, but unfortunately that update has not been published in a format that we can use in Business Ops (see [Issue #109](https://github.com/microsoft/Analysis-Services/issues/109#issuecomment-1071973096) in the Analysis Services repo for more details). 

I've already commented on that issue letting Kay know that we need an updated MSI for Business Ops, but haven't heard back. Please feel free to add your own voice to the discussion there, and perhaps that will help get the ball rolling again.

James

**Comment by JamesDBartlett3** [comment]
@mrkorki Metadata Translator has been updated to the latest version in [Business Ops 3.0.3](https://powerbi.tips/product/business-ops/).
