### ISSUE TITLE
Blank window when I click on either "Add External Tools" or "Edit External Tools"

### ISSUE THREAD

**Issue by CuriousGeoSq** [MikeCarlo/BusinessOps#14]
Greetings!

I have installed Business Ops 3.0.2 on two machines, on both of which I have admin privileges. The app will launch fine (first screenshot). But as soon as I click on either "Add External Tools" or "Edit External Tools" the app screen will go blank, other than the title bar, as seen in the second screenshot. Any advice?

Also, it appears this repo doesn't mention version 3.0.2, but I may have missed that.

![Business Ops 3 0 2 Home screen](https://user-images.githubusercontent.com/50724147/160672925-33cb58c9-0eea-4849-90b9-0f1540713de6.PNG)

![Business Ops 3 0 2 Add External Tools](https://user-images.githubusercontent.com/50724147/160672952-17a62b33-6baa-453b-9771-8fe4d50fb6b6.PNG)

**Comment by JamesDBartlett3** [comment]
Hi @CuriousGeoSq, 

Can you provide some more details about the systems you're using, such as OS version, language settings, etc?

Also, can you try opening the Dev Tools panel in Business Ops (Ctrl+Shift+I), and see if you can spot any error messages in the console when you navigate to the Add or Edit External Tools pages?

Thanks!

James

**Comment by CuriousGeoSq** [comment]
Screenshot attached. 

While running Business Ops I opened Dev Tools, then clicked on “Add External Tools”.

Would JavaScript have anything to do with this?

No error messages.

 

Nothing peculiar about my system.

Windows 10 Enterprise 21H2

Windows Feature Pack Experience

8GB RAM

English only

 

I have another machine running Windows 10 Pro, 21H1, 16GB RAM

Identical experience

**Comment by JamesDBartlett3** [comment]
Hi @CuriousGeoSq, we've done a major overhaul of the BusinessOps codebase since this ticket was opened. Can you install [the latest version](https://github.com/MikeCarlo/BusinessOps/releases/latest) and let us know if you're still experiencing this issue?

**Comment by CuriousGeoSq** [comment]
I'm so excited...THIS WORKED! I have version 3.1.5. Fantastic. Thank you for the notification! 
 
  
 
 
 

-----Original Message-----

From: James ***@***.***>
To: MikeCarlo ***@***.***>
Cc: CuriousGeoSq ***@***.***>; Mention ***@***.***>
Date: Wednesday, 9 October 2024 4:20 PM EDT
Subject: Re: [MikeCarlo/BusinessOps] Blank window when I click on either "Add External Tools" or "Edit External Tools" (Issue #14)

 

  Hi @CuriousGeoSq, we've done a major overhaul of the BusinessOps codebase since this ticket was opened. Can you install the latest version and let us know if you're still experiencing this issue? —

**Comment by JamesDBartlett3** [comment]
@CuriousGeoSq Awesome, glad to hear it! I'm closing this issue now, but please feel free to let us know if it starts happening again.

**Comment by CuriousGeoSq** [comment]
Roger that, Mike! Thanks again! 
  
If it's easy to answer, I'm curious about the change(s) that were made so that the app works now on my machine. 
 
  
 
 
 

-----Original Message-----

From: James ***@***.***>
To: MikeCarlo ***@***.***>
Cc: CuriousGeoSq ***@***.***>; Mention ***@***.***>
Date: Sunday, 13 October 2024 9:46 PM EDT
Subject: Re: [MikeCarlo/BusinessOps] Blank window when I click on either "Add External Tools" or "Edit External Tools" (Issue #14)

 

  @CuriousGeoSq Awesome, glad to hear it! I'm closing this issue now, but please feel free to let us know if it starts happening again. —

**Comment by MikeCarlo** [comment]
We updated many of the code dependencies, so lots of package upgrades.  Likely some of the older packages were losing support on various machines.

**Comment by CuriousGeoSq** [comment]
Gotcha. Thank you for the reply! 
 
  
 
 
 

-----Original Message-----

From: Mike ***@***.***>
To: MikeCarlo ***@***.***>
Cc: CuriousGeoSq ***@***.***>; Mention ***@***.***>
Date: Monday, 14 October 2024 1:54 PM EDT
Subject: Re: [MikeCarlo/BusinessOps] Blank window when I click on either "Add External Tools" or "Edit External Tools" (Issue #14)

 

  We updated many of the code dependencies, so lots of package upgrades. Likely some of the older packages were losing support on various machines. —
