### ISSUE TITLE
Please add "Power BI Sidetools" from TheBIPower

### ISSUE THREAD

**Issue by didierterrien** [MikeCarlo/BusinessOps#2]
Hello Mike,
I suggest you add "Power BI Sidetools" from TheBIPower.
Power BI Sidetools allows you to manage your DAX and M formulas in Visual Studio Code. Measures, calculated columns & tables, Power Query queries can be viewed with syntax highlighting and/or intellisense. 
More functionalities will come soon.

Visual Studio Code brings powerful capabilities like search and replace, formulas comparison, themes, snippets, backup, collaboration, GIT, ...

Please have a look at this page : [https://thebipower.fr/index.php/power-bi-sidetools/](https://thebipower.fr/index.php/power-bi-sidetools/)
Best regards

**Comment by didierterrien** [comment]
Hello Mike,

Coming with version 1.1.0, Power BI Sidetools exports your data into Excel with only one click. Then you can setup pivot tables, add theme & graphics, macros and do whatever you want. You can even generate a paginated report. Next time you will open this file from Power BI Sidetools, it will be refreshed and you will keep all the setup you did previously. Super quick and super efficient in few steps.

![](https://thebipower.fr/wp-content/uploads/2020/10/Export-to-Excel-1536x621.png)
Regards

**Comment by MikeCarlo** [comment]
The prior link wasn't working for me.  

I'll take a look for adding this tool.  Thanks for the suggestion.

**Comment by didierterrien** [comment]
Thanks, I corrected the URL. Let me know about your experience.

**Comment by didierterrien** [comment]
Hello Mike,
Coming with version 1.1.4 : create and manage your external tools ignoring everything about Json and base64 formats. Try the wizard and create your own external tool in one minute. 
Merry Christmass !

https://thebipower.fr/index.php/2020/12/01/manage-your-external-tools/

![External tools manager](https://user-images.githubusercontent.com/37301981/102070415-62e40e80-3dff-11eb-8ee2-1abf5d26209f.png)

**Comment by JamesDBartlett3** [comment]
Came here to upvote this suggestion. Power BI Sidetools is extremely useful, especially now that it comes with that external tools manager. Highly recommended.

**Comment by didierterrien** [comment]
Hello Mike,
Power BI Sidetools 1.2.0 is published. The exclusive DAX debugger appears in preview. Feel free to comment and give new ideas :   [https://thebipower.fr/index.php/power-bi-sidetools/](https://thebipower.fr/index.php/power-bi-sidetools/)
I'm honored to showcase it with Reid Havens on April 9th : [https://bit.ly/3dyeIdr](https://bit.ly/3dyeIdr)

![DAX debugger](https://user-images.githubusercontent.com/37301981/113902841-9db7eb00-97d0-11eb-933c-63599ba3597c.png)

**Comment by didierterrien** [comment]
That's done. Thank you Mike
