### ISSUE TITLE
Unable to Themes, & Charts and other tools - Business Ops Setup 0.0.11

### ISSUE THREAD

**Issue by ank-rapmap** [MikeCarlo/BusinessOps#5]
Hello there, 

I have used the PowerBI.tips Business Ops Setup 0.0.11 to add external tools, the following highlighted tools are not working. 

![image](https://user-images.githubusercontent.com/73853409/103383572-5114a200-4b47-11eb-8731-39955cdeb778.png)

I am getting an error shown below: 

![image](https://user-images.githubusercontent.com/73853409/103383600-6be71680-4b47-11eb-827a-9edef3996c13.png)

Please assist, am I missing any step.

Cheers,
Ankit

**Comment by ank-rapmap** [comment]
Hi Mike, I just realised, this is the issue with "Google Chrome" tools, as I can open the Edge custom tools. 

Can you please let me know to disable/remove tools in PowerBI?

Cheers,
Ankit

**Comment by MikeCarlo** [comment]
Check out the instructions on the home page to delete out External Tools from the Power BI directory: 
https://github.com/MikeCarlo/BusinessOps#uninstall-external-tools-from-power-bi-desktop

This will let you delete the files you don't want.
