### ISSUE TITLE
Dax.Guide Chrome Executable not working from PBI External Tools

### ISSUE THREAD

**Issue by KJM0123** [MikeCarlo/BusinessOps#6]
When attempting to launch Dax.guide Chrome from the Power BI External Tools ribbon, I receive an error message indicating "DAX.Guide Chrome executable not found. Contact the tool author for support."  Not sure if there is something relative to my computer's settings that is prompting this error, or if this is a problem with the link/tool itself.  In any case, I need to know how to remove the Dax.guide Chrome external tool since it doesn't currently work.

**Comment by didierterrien** [comment]
You can try to modify the Json file this way in order to open the Url in your default browser :

![image](https://user-images.githubusercontent.com/37301981/109969663-744d0080-7cf4-11eb-82e5-53ce70eb8964.png)

**Comment by MikeCarlo** [comment]
I like this idea, 

@KJM0123 and @didierterrien  
would you prefer for the page to open in the default browser of the PC, or do you want the choice to choose Chrome, Edge or Internet Explorer?

**Comment by didierterrien** [comment]
I personally prefer to open Web pages in the default browser.

**Comment by KJM0123** [comment]
@didierterrien - thank you for the response you provided.  I had actually moved on to other/bigger problems just after my posting and had forgotten about this until now we received Mike's response today.  Admittedly, I'm a novice when it comes to the programming, json files, etc., so I didn't think to look at the arguments in the json file to see if that was the root cause of the issue.  Your comment prompted me to look at the json file, and what I found was simply that the path to Chrome.exe wasn't correct - at least not for where Chrome was loaded on the machine I use (pointing to 'Program Files (x86)' instead of just 'Program Files'.  In short, changing the Path to the executable resolved the issue I was having.

@MikeCarlo - having noted the above, I also like the idea of the tool just using the default browser of the PC.  I'd be curious if this would help avoid the problem with the path that I noted above.

**Comment by JamesDBartlett3** [comment]
@KJM0123 & @didierterrien, [the latest version of BusinessOps](https://github.com/MikeCarlo/BusinessOps/releases/latest) now launches all web links in the default web browser specified in the operating system settings. Hope this helps!
