### ISSUE TITLE
PBI.tips issue: "Themes executable not found. Contact the tool author for support." I installed chrome supported add on and I have Chrome browser.

### ISSUE THREAD

**Issue by Salil007** [MikeCarlo/BusinessOps#7]

**Comment by MikeCarlo** [comment]
I would recommend removing the External Tool icon from the ribbon, then re-adding it.  

We made some internal changes to the Business Ops tool that moved around some assets, the movement of those internal assets might have caused something to break. 

If that doesn't work, Try un-installing Business Ops then re-installing the latest version.  

The only other thing I can think of is that the chrome install location is different on your machine that it was on mine. or Google moved the EXE file to run Chrome.

**Comment by MikeCarlo** [comment]
I have been able to reproduce the issue.

**Comment by MikeCarlo** [comment]
I think the PBITools.json file is broken as the google chrome install location now seems to be in Program Files vs. Program Files (x86) as called out in the json file. 

**new**
![image](https://user-images.githubusercontent.com/25160592/116254135-b57ef100-a736-11eb-8b1a-ffe2bf905007.png)

**old**
![image](https://user-images.githubusercontent.com/25160592/116254191-c2034980-a736-11eb-9163-d67dc79249c3.png)

I will add this to our backlog to fix...

**Comment by Salil007** [comment]
Did everything but the problem and error message still remains the same.
I reinstalled the software and removed and readded the business ops tool
along with other for quite a few times.
But unable to use them.

**Comment by moltra** [comment]
To fix this problem, you need to edit the json file in the following folder.  

"C:\Program Files (x86)\Common Files\Microsoft Shared\Power BI Desktop\External Tools\"

This is the correct information for my computer for chrome.
"C:/Program Files/Google/Chrome/Application/chrome.exe"
Make sure you notice that the Slashes are different.

you need to do this for each one that uses Chrome.

I would submit a change request, but the code is private.

**Comment by JamesDBartlett3** [comment]
@Salil007 & @moltra, [the latest version of BusinessOps](https://github.com/MikeCarlo/BusinessOps/releases/latest) now launches all web links in the default web browser specified in the operating system settings. Hope this helps!
