### ISSUE TITLE
add VertiPaq Analyzer

### ISSUE THREAD

**Issue by rootsmusic** [MikeCarlo/BusinessOps#9]
Please add [VertiPaq Analyzer](https://www.sqlbi.com/tools/vertipaq-analyzer/), which is useful to analyze VertiPaq storage structures for a data model in Power BI.

**Comment by asjones987** [comment]
I am confused I did not see VertiPaq Analyzer added?  I figured it would be under the SQL BI grouping.... I did see two versions of Analyze in Excel when the old could be dropped.
